name: CI for Merges to Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t myapp:latest .

    - name: Basic Test Step
      run: echo "Running basic tests... Success!"

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PAT_TOKEN }}

    - name: Push Docker image
      run: |
        docker tag myapp:latest ghcr.io/hiuston957/myapp:latest &&
        docker push ghcr.io/hiuston957/myapp:latest
